# Generated by Django 3.2.14 on 2024-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_split', models.CharField(choices=[('train', 'train'), ('test', 'test')], max_length=5)),
                ('data_type', models.CharField(choices=[('normal', 'normal'), ('error', 'error')], max_length=6)),
                ('data_folder', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('file_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pipe_image_data',
                'managed': False,
            },
        ),
    ]
